### ISSUE TITLE
additional data filters?

### ISSUE THREAD

**Issue by treerunner** [Omaroid/Covid-19-API#5]
Thanks so much for this. I am going to switch to use this API. Is it ok if I use directly for my simple application?

A question for you: Would it be possible to extend the API to include filter by location (country or province)? If so that would reduce overhead for any users like myself that would like to slice the data down to more specific needs.

So, the endpoint could potentially be:
/confirmed/countrycode
/confirmed/countrycode/province

or something along those lines.

Also, for date: 2020-01-22 preferable to 1/22/20 -but not a big deal.

Thanks again!

**Comment by Omaroid** [comment]
Hello!

Of course you could use my API for your personal or academic projects! I'll try to extend the API so it could be more specific for a country or a country's province and also for the date format. I'll work on that on the next few days! 

I'll keep your issue marked as open till I make some improvements on the API.

Thank you!

**Comment by Omaroid** [comment]
I've released a new version today, you could check the README. It may answer your questions about queries concerning a specific country 😉

> Thanks so much for this. I am going to switch to use this API. Is it ok if I use directly for my simple application?
> 
> A question for you: Would it be possible to extend the API to include filter by location (country or province)? If so that would reduce overhead for any users like myself that would like to slice the data down to more specific needs.
> 
> So, the endpoint could potentially be:
> /confirmed/countrycode
> /confirmed/countrycode/province
> 
> or something along those lines.
> 
> Also, for date: 2020-01-22 preferable to 1/22/20 -but not a big deal.
> 
> Thanks again!

I've released a new version today, you could check the README. It may answer your questions about queries concerning a specific country 😉
