### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by treerunner** [Omaroid/Covid-19-API#6]
SyntaxError: JSON.parse: unexpected character at line 1 column 173620 of the JSON data

...

Parse error on line 1:
.../16/20":0,"3/17/20":NaN,"3/2/20":0,"3/3/
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

empty cells in the csv?

**Comment by Omaroid** [comment]
Hello,

The API returns "nan" in case of a row who doesn't have a province name. This is the case of all other countries than US or China and also for small countries. The data I use for the API is provided by [JHU CSSE](https://github.com/CSSEGISandData/COVID-19) so I don't know why they don't include provinces for other countries. Also for the dates, they are in the format of mm/dd/yy.

I'll close the issue. Thank you
