### ISSUE TITLE
Upcoming Changes in Time Series

### ISSUE THREAD

**Issue by treerunner** [Omaroid/Covid-19-API#7]
Heads up:

https://github.com/CSSEGISandData/COVID-19/issues/1250

> Three new time series tables will be added for the US. The first two will be the confirmed cases and deaths, reported at the county level. The third, number of tests conducted, will be reported at the state level.

> Changes to the current time series include the removal of the US state and county-level entries, which will be replaced with a new single country level entry for the US.

By the way - Thanks for this API. It's working well for me. I've refactored my code and it's quite a bit more efficient than before.

**Comment by Omaroid** [comment]
Nice to know it, i'll improve the code in the next few days.
