### ISSUE TITLE
JSON parse error in "confirmed" endpoint

### ISSUE THREAD

**Issue by balsama** [Omaroid/Covid-19-API#8]
Hi. Thanks for putting this together.

The response from https://covid19api.herokuapp.com/confirmed is returning invalid json currently. Specifically:

```
Error: Parse error on line 15322:
...": 0,			"3/23/20": NaN,			"3/3/20": 0,
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

**Comment by stopyransky** [comment]
yeah i think issue is related to  the source https://github.com/CSSEGISandData/COVID-19/issues/1372
seems that they tried to add granulation to US data but messed the whole dataset.
IT seems that now timeseries files are depreciated  and will not be updated - they use different files:
info here: https://github.com/CSSEGISandData/COVID-19/issues/1355

**Comment by Omaroid** [comment]
I've corrected the files to support the new changes in the dataset. Check the readme for more details.
